### ISSUE TITLE
feature: load connectome from CSV

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue#713] opened 2023-10-04 14:56 UTC

**Comment by hanayik** [comment] 2023-11-15 13:35
@cdrake , is this still a work in progress?

**Comment by neurolabusc** [comment] 2024-04-18 18:35
Closing this, but we may want to revisit as [BIDS BEP017](https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit) matures. The proposal is for using TSV files for data. I do have personal reservations of separating a single connectome into multiple files (especially as sandboxed web applications do not have permission to read a `.tsv` file if the user drops a `.json` onto the viewer). However, we should support community formats, even if they are not our preferred format.

**Closed by neurolabusc** 2024-04-18 18:35 UTC
Labels: enhancement

**Comment by eduff** [comment] 2024-07-08 10:07
I'd be interested in assisting with getting some sort of integration with the proposed BIDS BEP017 format - would a converter perhaps built into one of the BIDS utilities be the best approach for now do people think?  Or something independent that can handle more of a variety of csv type formats?

**Comment by hanayik** [comment] 2024-07-08 10:21
@eduff  and @neurolabusc , we can easily load both .tsv and .json files using URLs (e.g. for openneuro.org) or other hosted data. The proposed directory and file structure in BEP017 would allow automatically loading the .json file as long as the .tsv and .json files have the same URL (with the only change being the file extension between the two files). 

We already support this type of automatic file loading with AFNI .BRIK and .HEAD files. For example, if a user loads only a .HEAD URL then we automatically check for the paired .BRIK file at the same URL. 

However, file drag and drop would still be a problem as pointed out by @neurolabusc. To support file drag and drop, users would need to drop both .tsv and .json files onto the NiiVue canvas rather than one at a time. We could implement that logic if needed.

**Comment by neurolabusc** [comment] 2024-07-08 15:10
@eduff as Taylor notes, adding support possible, but I would encourage you to think about whether the proposed format is suitable for web usage. A major feature of web pages is that they live in a `sandbox` and by design providing access to one file does not provide permission to access of other files (or even inspect the file hierarchy of folders). The major strength of this approach is privacy and security: a web page can not read private details for your computer. However, this has major limitations for data where information is stored in multiple files (e.g. with BIDS a NIfTI image `img.nii.gz` often has a paired JSON sidecar `img.json`). The BIDS [inheritance principle](https://bids-specification.readthedocs.io/en/stable/common-principles.html#the-inheritance-principle) further complicates this as the sidecar may have a different name and may be in a parent folder. In general, storing data across multiple files can also frustrate users if only one file is copied.

I recognize there are tradeoffs for reducing redundancy and having a human readable structure. However, it is worth considering that the current BEP017 always segments connectomes into multiple files and it will be the responsibility of the backend to provide **any** web-based tool (NiiVue or other) with access to all the components to support this. You might want to consider whether one can use multiple files or optionally embed all the information (node positions, node weights, edge weights, etc) in a single file. This would mirror [NRRD](https://teem.sourceforge.net/nrrd/format.html), NIfTI (e.g. .nii vs .hdr/.img), [MRtrix](https://mrtrix.readthedocs.io/en/dev/getting_started/image_data.html#mrtrix-image-formats-mih-mif) (mif vs mih) that provide options for single file and multiple file representations. While multiple files might be useful for large repositories like OpenNeuro that support the back end logic, a single file version would allow users to easily share a file that would provide reproducible results and simple drag-and-drop support.

As a final comment, I would discourage the choice of zarr and h5 for compression. I would urge you to keep it simple to aid dissemination. It is worth noting that while NiiVue supports over 30 formats for meshes, connectomes, streamlines and images, embeds scalable fonts, includes many advanced shaders, and high performance compression, [over half of the code](https://github.com/niivue/niivue/issues/746) is devoted to supporting just the DICOM format and its complex transfer syntaxes. I think the main reason BIDS/NIfTI succeeded instead of DICOM is this complexity - otherwise DICOM offers huge advantages. Do consider some of the criticisms of [HDF5](https://cyrille.rossant.net/should-you-use-hdf5/) and [HDF5 corruption](https://janert.me/blog/2022/looking-at-hdf5/). Python users have great libraries they can install for these, but any web support will require a large amount of overhead to support these and may cause adoption and maintenance issues. While typical gzip implementations do not support random access, it is ubiquitous an has served NIfTI well.

**Comment by eduff** [comment] 2024-07-08 15:30
Thanks, I fully understand and I'll think about this.  Most of the decisions about format have been driven by (developing) conventions at a higher level of the BIDS hierarchy unfortunately, and many competing connectivity dataset types, and this is all difficult to direct.  What I was suggesting now was more of an ad-hoc converter to the json format you demonstrated - this would at least be useful to emphasise use cases of the final format, which is not as much of a focus as it should be.
