### ISSUE TITLE
Colormap of hippo.nii.gz or hippolr.nii.gz volume cannot be changed.

### ISSUE THREAD

**Issue by cdrake** [niivue/niivue#1008] opened 2024-06-25 15:23 UTC
Colormap of hippo.nii.gz or hippolr.nii.gz volume cannot be changed. 

An initial colormap can be loaded but after updateGLVolume is called the volume disappears.

Steps to reproduce:
- Modify the colormaps.html demo file to load hippo.nii.gz or hippolr.nii.gz.  
- Select a different colormap

The image will disappear after a colormap is selected.

**Comment by hanayik** [comment] 2024-06-26 11:38
@cdrake , I have tried to reproduce using the steps you listed. 

- I edited `colormaps.html` to load `hippo.nii.gz` by default as gray
- I then clicked on `bluegrn` button to change colormap and the result looked correct. 
- I tested in safari, chrome, and firefox

## before changing colormap
<img width="1278" alt="Screenshot 2024-06-26 at 12 32 57" src="https://github.com/niivue/niivue/assets/5217720/f75be8ed-a49c-4091-bd40-3693d79e4108">

## after changing colormap
<img width="1274" alt="Screenshot 2024-06-26 at 12 33 11" src="https://github.com/niivue/niivue/assets/5217720/cb3e7728-8930-47cc-973d-3f63a8da2736">

**Comment by neurolabusc** [comment] 2024-06-26 12:09
@hanayik this issue is now fixed, as part of the recently merged pull request. I should have referenced this issue with this [commit](https://github.com/niivue/niivue/pull/1006/commits/3b7b9b3c7b78effad393aab213f8a8dd51461494). It is an unusual edge case where the image is binary (all values are either zero or nine), but it is not integer based, nor are the two values the typical zero or one. This interaction of properties caused the first calMinMax() to suggest ignoring zeros (because they are so plentiful), causing the second call to assume one intensity. It is certainly wasteful to store binary masks as float32 (indeed, MRtrix uses 1-bit per voxel for these types of images). However, float32 is the default datatype for popular tools like fslmaths, so our robust range algorithm should handle this.

My fix is minimal. The function calMinMax() is computationally slow, and the only reason it is called by setColormap() is to handle situations where one selects a calibrated colormap (e.g. our CT colormaps that set Hounsfield units) or when one switches from a calibrated colormap to an uncalibrated colormap. As an optimization, we could add a few lines of code to detect those specific situations.

**Closed by neurolabusc** 2024-06-26 12:09 UTC
