### ISSUE TITLE
Unable to Achieve Intermediate Opacity When Modifying Alpha Values in Colormap

### ISSUE THREAD

**Issue by Appryll** [niivue/niivue#1085] opened 2024-10-21 07:34 UTC
Hello,

I’m trying to adjust the opacity of a specific region in my volume by modifying the alpha values in my colormap, but the changes are not reflected in the image.

My goal is to make the selected region fully opaque, while setting the other regions to an intermediate opacity level.

To achieve this, I first created an RGBA colormap JSON with all alpha values set to 125. However, there were no visible changes in the image’s opacity, which remains fully opaque.

I also followed the demo's example [Voxel atlas](https://niivue.github.io/niivue/features/atlas.html) Starting from my RGB colormap (my RGBA without the alpha channel), I obtained the LUT and set the fourth value (index 3) for all regions to 96, and for the selected region to 200 (lut[(index * 4) + 3]). Although I can see the LUT values changing in the console, there is no effect on the image’s opacity. However, if I adjust the R, G, and B values, the color changes, but not the opacity.

Continuing my attempts, I created a function that, when a region is selected, adds the "A" key to my RGB colormap. It uses the same number of values as "R" (and "G" and "B"), setting them to 125, except for the selected region’s alpha value, which is set to 255. Despite these changes, there was no effect on the opacity. The only changes I observe occur when setting alpha values to 0 or 255 (transparent and fully opaque), but this is not what I’m aiming for. I would like to achieve an intermediate opacity for the non-selected regions.

I also tried using an RGBAI colormap but encountered the same outcome. The opacity only changes when the alpha values are set to 0 or 255, not with intermediate values.

I don’t understand what might be going wrong. Is it possible that opacity adjustments are limited to predefined colormaps in niivue? Could you please help me with this functionality?

Thank you for your assistance.

**Comment by neurolabusc** [comment] 2024-10-21 10:47
@Appryll this is the intended behavior. You can find out more details in the [colormaps](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md) developer notes.
 1. As you found with the voxel atlas live demo](https://niivue.github.io/niivue/features/atlas.html), the alpha blending is controlled by a single opacity value, in this example [setOpacity()](https://github.com/niivue/niivue/blob/d4fe67d67eb332995a8f6979a7951ee187e3e213/demos/features/atlas.html#L91). Therefore, the colormap's alpha value only distinguishes between transparent (0) and opaque (any other value).
 2. The voxel alpha value influences the volume rendering. Voxels can vary from being almost completely transparent (like a cloud, that has no hard surface) all the way to being completely opaque (like the hard surface of a rock). You can see this influence in the [colormaps live demo](https://niivue.github.io/niivue/features/colormaps.html) where you can compare a translucent surface:
```
let cmap = {
 R: [0, 255],
 G: [0, 255],
 B: [0, 255],
 A: [0, 22],
 I: [0, 255],
};
```
to an opaque one:
```
let cmap = {
 R: [0, 255],
 G: [0, 255],
 B: [0, 255],
 A: [0, 255],
 I: [0, 255],
};
```
![blend](https://github.com/user-attachments/assets/55f562c4-5092-4c62-ba78-dc3eab261ebd)


You can make sub-threshold voxels translucent by using the alphaThreshold property, as shown in the [alphathreshold live demo](https://niivue.github.io/niivue/features/alphathreshold.html) which uses the method [described here](https://pubmed.ncbi.nlm.nih.gov/37116766/).

**Comment by Appryll** [comment] 2024-10-21 12:57
@neurolabusc Thank you for your quick response and the information provided.

Does this mean that with the following colormap, I should get a volume with completely opaque regions?
```
let cmap = {
  R: [0, 255, 24, 170],
  G: [0, 76, 128, 170],
  B: [0, 62, 100, 170],
  A: [0, 125, 125, 125],
  labels: ["air", "reg_1", "reg_2", "reg_3"]
};
```
Because that is exactly what I am getting a volume with fully opaque regions. However, I can still adjust the volume's opacity without any issues using setOpacity() as you described.

Regarding the [voxel atlas live demo](https://niivue.github.io/niivue/features/atlas.html), I understand that when the mouse hovers over a region, the LUT changes and modifies the alpha value to 200, which makes the region stand out from the rest. This is exactly what I'm trying to achieve, but I haven't been able to replicate it. 

With the following colormap, wouldn’t I obtain regions with different colors and opacities?

```
let cmap = {
  R: [0, 255, 24, 170],
  G: [0, 76, 128, 170],
  B: [0, 62, 100, 170],
  A: [0, 255, 125, 50],
  labels: ["air", "reg_1", "reg_2", "reg_3"]
};
```

Thank you for your time.

**Comment by neurolabusc** [comment] 2024-10-21 13:43
The [colormaps for labelled images are described here](https://github.com/niivue/niivue/blob/main/docs/development-notes/colormaps.md#atlases-and-labeled-images) and you can try them out with this [atlas live demo](https://niivue.github.io/niivue/features/segment.html). 

Note that for the 2D slices, alpha compares zero versus non-zero, so making gray transparent

```
let cmap = {
 R: [0,   0, 120, 175],
 G: [0,  90,  60, 185],
 B: [0, 120,  60, 175],
 A: [0, 1,  0, 1],
 labels: ["air","CSF","gray","white"],
};
```
versus opaque (with 1..255 giving the same result), with the setOpacity slider adjusting the translucency of all regions with non-zero values.
```
let cmap = {
 R: [0,   0, 120, 175],
 G: [0,  90,  60, 185],
 B: [0, 120,  60, 175],
 A: [0, 1,  1, 1],
 labels: ["air","CSF","gray","white"],
};
```

**Comment by neurolabusc** [comment] 2024-10-30 18:07
I am still not sure I understand the question. I do think that this [live demo](https://niivue.github.io/niivue/features/atlas.html) illustrates how you can set the `colormapLabel.lut` color lookup table (lut) with custom alpha. Note that colormapLabels differ a little bit from traditional colormaps. One typically uses trilinear interpolation for scalar color maps (a pixel half way between voxels with brightness 5 and 7 could be reasonably estimated as having an intensity of 6; a pixel half way between Brodmann Areas 5 and 7 must use nearest neighbor as it is not area 6). Make sure your [NIfTI atlas](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) uses the NIFTI_INTENT_LABEL.

**Comment by hanayik** [comment] 2024-11-17 20:01
@Appryll , I'm closing this for now. Let us know if it would be better to keep the issue open.

**Closed by hanayik** 2024-11-17 20:01 UTC
