### ISSUE TITLE
loadDrawingFromUrl  vs  loadVolumes

### ISSUE THREAD

**Issue by johnren-code** [niivue/niivue#616] opened 2023-06-06 06:22 UTC
Thanks for your awesome work!

When I use `loadDrawingFromUrl` and `loadVolumes` , I have a few questions.

When I use `loadDrawingFromUrl` to import a file that records tags, `nv.loadDrawingFromUrl("/api/image/202302/0b2be9e0-886b-4144-99f0-8bb4c6eaa848-label.nii.gz")` , the result is this:
![image](https://github.com/niivue/niivue/assets/76835772/b07e3c2d-a1a3-4ed9-8041-b83f6d0fe641)

When I use loadVolumes to import the same, the result is this (without color):
![image](https://github.com/niivue/niivue/assets/76835772/def2f4c4-050b-424c-8fa6-81f4422796e5)

When I use both stacked together, the result is as follows:
![image](https://github.com/niivue/niivue/assets/76835772/512dd3e3-011d-446f-90cf-b8c77e7ccecb)

We can see that overlaying the two gives a more three-dimensional and clear color effect, but this will cause some problems when we use the brush (because visually it is possible, but when we try to delete some blocks with the eraser, the part of the `loadVolume` display will be exposed), I would like to achieve this more three-dimensional and clear effect just by using `loadDrawingFromUrl`. I would like to use `loadDrawingFromUrl` only to achieve this more three-dimensional and clear effect, because `loadVolume` can not provide the function of a brush, so I would like to ask what kind of settings can be used only with `loadDrawingFromUrl` to achieve the last picture display effect? It also allows us to edit the colors with the brush

Looking forward to your reply!

**Comment by neurolabusc** [comment] 2023-06-07 20:18
@johnren-code I can provide more feedback if you provide a sample that allows me to replicate your setup . However, you describe the intended behavior.  Drawings are discrete: a voxel is or is not a specific color (so nearest neighbor interpolation is required). In contrast, scalar volumes can use trilinear interpolation to reduce aliasing. Put another way, the boundary of Brodmann Area 6 and 8 is **not** Area 7: the classification is discrete. In contrast, for scalar MRI T1 images, 7 is a reasonable partial volume estimate for a mixture of 6 and 8.

**Comment by johnren-code** [comment] 2023-06-08 08:14
Here is my code:
```
<template>
<div>
<canvas id="gl" height="480" width="640"></canvas>
</div>
</template>
const nv = new Niivue({
  logging: true,
  dragAndDropEnabled: true,
  backColor: [0, 0, 0, 1],
  show3Dcrosshair: true,
  // onLocationChange: this.locationChangeHandler,
})
export default {
  name: 'Segmentation',
  data() {
    return {
      volumeList: [
        {
          url: "/api/image/202302/0b2be9e0-886b-4144-99f0-8bb4c6eaa848.nii.gz",
        }
      ],
    }
  },
mounted() {
    nv.setInterpolation(false)
    nv.setRadiologicalConvention(false)
    nv.opts.multiplanarForceRender = true
    nv.attachTo('gl')
    nv.loadVolumes(this.volumeList)
    nv.setSliceType(nv.sliceTypeMultiplanar)
    nv.setClipPlane([0.3, 270, 0]);
    nv.setRenderAzimuthElevation(120, 10);
    nv.setSliceMM(true);
    nv.graph.autoSizeMultiplanar = true
    // nv.loadDrawingFromUrl(this.testUrl)
    nv.loadDrawingFromUrl("/api/image/202302/0b2be9e0-886b-4144-99f0-8bb4c6eaa848-label.nii.gz")
    nv.drawMeasurementTool()
    // nv.overlayRGBA()
  }
```
I would be grateful if you could suggest something to achieve the above effect.

**Comment by johnren-code** [comment] 2023-06-08 08:43
The files I use is available at [](https://drive.google.com/drive/folders/1kE5ibPsqhlxJWbjbquSFCsKbneljcR1u?usp=drive_link). `0b2be9e0-886b-4144-99f0-8bb4c6eaa848.nii.gz` is the original file, `0b2be9e0-886b-4144-99f0-8bb4c6eaa848-label.nii.gz` is the label file after 3D segmentation of it

**Comment by neurolabusc** [comment] 2023-06-08 13:20
@johnren-code this is the intended behavior. The drawing colors are categorical, not scalar. The images below show the effect of using trilinear (top) versus nearest-neighbor (bottom) interpolation for your drawing. 
 1. As you have found, one solution would be to load the drawing as both a categorical drawing as well as a scalar grayscale image.
 2.  Future versions of NiiVue will introduce optional shaders that will apply gradient-based lighting shaders, as we [demonstrate in this live demo](https://rordenlab.github.io/) that will also provide hinting. However, this method requires substantially more resources, and our focus has been to provide interactive graphics even on low-end devices.


![linear](https://github.com/niivue/niivue/assets/8930807/d7f0ed28-17d9-4b9f-923f-e0741cdc89b7)
![nearest](https://github.com/niivue/niivue/assets/8930807/e7286592-3f20-47af-8a80-5a7c5f483da7)

**Comment by johnren-code** [comment] 2023-06-08 13:47
Ok, thanks for the explanation, I understand, how is the trilinear interpolation shown in your picture above achieved? I think the effect achieved by trilinear interpolation meets my needs.

In addition, for solution 1, the superimposed effect to achieve a visual three-dimensional sense, which will make the user in the eraser to delete a certain area, resulting in categorical drawing and scalar grayscale image both out of sync, so I do not have a better measure for the superimposed method.

I'm also thinking about some possible solutions to this problem, and I'll be happy to share them with you if I can finally come up with a workable solution.

**Comment by johnren-code** [comment] 2023-06-08 13:50
In fact, the overlay effect I show in the image is only achieved by loading the same file as `loadDrawingFromUrl` and `loadVolume`.

**Comment by neurolabusc** [comment] 2023-06-08 13:52
You can make your own fork of NiiVue and update the function [drawImage3D()](https://github.com/niivue/niivue/blob/8d686ceb9f5955a45dc9e4807bd9db1def27caec/src/niivue.js#L7450) to support linear interpolation:
```
    if (this.drawBitmap && this.drawBitmap.length > 8) {
      let interp = this.gl.LINEAR;
      this.gl.activeTexture(this.gl.TEXTURE7); //overlay
      this.gl.texParameteri(this.gl.TEXTURE_3D, this.gl.TEXTURE_MIN_FILTER, interp);
      this.gl.texParameteri(this.gl.TEXTURE_3D, this.gl.TEXTURE_MAG_FILTER, interp);
      gl.uniform1f(shader.drawOpacityLoc, this.drawOpacity);
    } else gl.uniform1f(shader.drawOpacityLoc, 0.0);
```

Precisely, you can get the effect by loading the same volume as both a scalar and indexed volume. Note that this doubles the resources required on your GPU.

**Comment by johnren-code** [comment] 2023-06-08 13:56
Ok, thanks for the answer, I will try this method later. In fact, I am currently using niivue library to make a complete 3D medical data presentation platform, if it goes well, I will open source my code on top of github when I finish, hopefully it will bring some help to niivue library.

Thanks again for your awesome work!

**Comment by johnren-code** [comment] 2023-06-08 17:12
I noticed that the color of the 2d slice is fine, the color of the 3d model obtained by trilinear interpolation is a bit problematic, what is the reason for this?
![image](https://github.com/niivue/niivue/assets/76835772/5f763ea1-72d4-4b9a-8270-0df7ce89dd67)

**Comment by neurolabusc** [comment] 2023-06-08 18:37
These are classic partial volume interpolation artifacts. The 2D slices show large contiguous regions of the same category, with artifacts only seen along the edge of the object. The 3D rendering is explicitly displaying the edges of the objects. The off-axes view of the rendering creates more partial volume voxels than sampling with the grid.

**Comment by johnren-code** [comment] 2023-06-09 02:54
Is there any way to solve this problem? For example, the corresponding code changes

**Comment by neurolabusc** [comment] 2023-06-15 14:33
@johnren-code I have added the ability to create custom labeled colormaps. You can try this out with this live demo. Note that the bottom left corner can provide the label name (e.g. bladder). It also provides a check box to toggle interpolation on and off. I do think for your situation you will want to use labeled images (as demonstrated) rather than drawings. Drawings are limited to 8-bits (256 levels) and are restricted (to allow rapid data transfer to the GPU).

```
git clone --branch issue616LiveDemo git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```

![issue616](https://github.com/niivue/niivue/assets/8930807/b60fb76b-6829-4d72-958a-7a3f39ad82b3)

**Comment by johnren-code** [comment] 2023-06-15 15:45
Ok, thank you very much for the example, it was very helpful for me! In fact, the reason I've been obsessed with using `loadDrawingFromUrl` is that I not only want to use colorMap to change the color, but I also want to use an eraser or brush etc. to do something editable with `volume[1]`, similar to `loadDrawingFromUrl`, is this possible?

**Comment by neurolabusc** [comment] 2023-06-16 14:34
@johnren-code I have added a new variable `renderDrawAmbientOcclusion`. The live demo now includes a slider that allows you to adjust this value between 0.0...1.0 - the default is 0.4.

```
git clone --branch issue616LiveDemo git@github.com:niivue/niivue.git
cd niivue
npm install
npm run dev
```

![ao](https://github.com/niivue/niivue/assets/8930807/52e5f4ae-e5b4-4e9a-aeeb-278c6e4e6089)

**Comment by johnren-code** [comment] 2023-06-16 15:25
I see, this is very helpful, thank you! Also, how do I add your changes to the nivue library I'm using for my current project, I'm using version 0.32.0 and the installation command in the vue framework is
`npm install @niivue/niivue@0.32.0`

**Comment by neurolabusc** [comment] 2023-06-16 17:38
I think @hanayik can provide a better answer. In the short term, you can compile your own copy of `niivue.umd.js` that you can use with your pages using the command:

```
git clone --branch issue616LiveDemo git@github.com:niivue/niivue.git
cd niivue
npm install
npm run demo
```

Longer term, if you are satisfied with this solution, please close this issue. At that stage, I will generate a pull request to the master branch. The PR will need to be reviewed and accepted to become part of the master branch. Once the PR is reviewed and approved, it will become part of the master branch.  At that stage, you can call it with:

```
<script src="https://niivue.github.io/niivue/features/niivue.umd.js"></script>
```

New releases are generated from the master branch, on an irregular schedule.

**Comment by johnren-code** [comment] 2023-06-17 12:49
OK, I will close this issue. Thank you very much for your help!

**Closed** 2023-06-17 12:49 UTC
