### ISSUE TITLE
can I change volume's matrix?

### ISSUE THREAD

**Issue by hezhongfeng** [niivue/niivue#654] opened 2023-07-24 06:37 UTC
I want to complete the following actions:：
1. Load multiple volumes
2. Using the mouse and keyboard to modify the matrix of a volume

Do you have these APIs?（get a volume's matrix and set(or save)matrix）

**Comment by neurolabusc** [comment] 2023-07-24 09:51
This is a [duplicate of issue 644](https://github.com/niivue/niivue/issues/644). This feature is not needed by any of the core features our team is working on. However, you can implement it yourself in a straightforward manner: 

1. Assuming your input image are voxels in the NIfTI format with a [valid s-form](https://brainder.org/2012/09/23/the-nifti-file-format/) for spatial orientation. Specifically, the s-form is a 3D 4x4 spatial transformation matrix. 
2. You can compute [affine transformations](https://en.wikipedia.org/wiki/Affine_transformation#Image_transformation) of translation, rotation, reflection, scale, and shear by multiplying the current sform by the desired 4x4 transformation matrix.
3. You can always write your own matrix multiplication, or call the [glmatrix mul() function](https://glmatrix.net/docs/module-mat4.html).
4. Re-Load your NIfTI image with the transformed s-form. NiiVue will automatically re-slice the overlay image onto the background image using the sforms of the two images.
5. Repeat these steps each time you wish to move your image.

**Comment by hezhongfeng** [comment] 2023-07-25 01:27
Thanks for your answer.

**Comment by hezhongfeng** [comment] 2023-07-26 06:06
I probably see what you mean and have the following questions:
1. how to get NIfTI image's transformed s-form?
2. how to Re-Load NIfTI image with the transformed s-form?

**Comment by hezhongfeng** [comment] 2023-07-26 06:06
@neurolabusc

**Comment by hezhongfeng** [comment] 2023-07-26 06:28
I think [this code](https://github.com/niivue/niivue/blob/349b34e971bcb06af23dfb68328a76fb67c0d11e/src/niivue.js#L6697) is to create a matrix

**Comment by neurolabusc** [comment] 2023-08-01 17:55
Precisely, NiiVue imports [gl-matrix](https://glmatrix.net/docs/module-mat4.html) 
 as `mat`, therefore `mat.mat4.create();` creates an 4x4 identity matrix, and it uses `mat.mat4.multiply()` to multiply matrices. While gl-matrix is has a nice set of matrix helper functions, you can also write your own. You can store the modified matrix in the [NIfTI](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) header as srow_x[4], srow_y[4], srow_z[4] (the final row of the 4x4 matrix is assumed to be [0,0,0,1]).

**Closed by neurolabusc** 2023-08-01 17:55 UTC
Labels: duplicate
