### ISSUE TITLE
Syncing Issues Between Sagittal, Coronal, and Axial Views 

### ISSUE THREAD

**Issue by anjugajbhiye91** [niivue/niivue#834] opened 2024-01-15 22:58 UTC
I want four different multiplanner views but with few UI changes So I have used four  grid for four view now the problem is 
Sagittal View Syncing Issue:
When crosshair moves of sagittal view is not syncing properly with coronal and but synching with axial views .

Axial View Syncing Issue:
Conversely, the axial view is not syncing as expected with both sagittal and coronal views on cosshair move.
 
but on crosshair move  of coronal view both sagittal and coronal are synching properly.

Could you please look into this matter and provide us with guidance on resolving these syncing discrepancies? If there are any updates, patches, or settings adjustments that we may have overlooked, we would greatly appreciate your assistance in rectifying this issue.
Plase follow below location to refer
Location: https://bitbucket.org/gajbhiyeanju/niivue-test/

**Comment by neurolabusc** [comment] 2024-01-16 08:34
@anjugajbhiye91 using four separate WebGL instances to display the same 3D volume is very inefficient. By design, NiiVue has a limited number of display options with our goal being to make it easier for users to transfer skills between different tools (AFNI, FreeSurfer, FSL). The design also focuses on using GPU resources efficiently.

I think what you want to do is natively accomplished by choosing the [grid layout](https://niivue.github.io/niivue/features/layout.html). That demo also shows you how you can force including a volume rendering, even if it reduces the size of the planar views. While I think this is beyond the scope of this question, you can also evaluate the [mosaic view](https://niivue.github.io/niivue/features/mosaics.html) which allows you to display an arbitrary number of planar slices and renderings. In general, our field uses mosaic (lightbox) views for static slices, but you could always add callbacks to synchronize views between slices.

**Comment by neurolabusc** [comment] 2024-01-17 13:51
I am closing this issue, but provide a simple demo to show how to sync axial, coronal, sagittal and rendering views across four instances of NiiVue. As I noted, this would be inefficient if all instances show the same volume (as I do here), but it provides a nice template for comparing different images, for example to check co-registration accuracy.

You can try this with:
```
git clone git@github.com:niivue/niivue.git
cd niivue
npm install
#replace /src/index.html with code below
npm run dev
```

with the following index.html file:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <title>Bidirectional Sync</title>
<style>
  html {
    height: auto;
    min-height: 100%;
    margin: 0;
  }
  body {
    display: flex;
    flex-direction: column;
    margin: 0;
    min-height: 100%;
    width: 100%;
    position: absolute;
    font-family: system-ui, Arial, Helvetica, sans-serif;
    user-select: none; /* Standard syntax */
    color: white;
    background: #202020;
  }
  header {
    margin: 10px;
  }
  footer {
    margin: 5px;
  }
  .page-wrapper {
    margin: 2px;
  }
  .row {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width: 100%;
    min-height: 100%;
    margin: 2px;
  }
  .column {
    display: flex;
    flex-direction: column;
    flex-basis: 100%;
    flex: 1;
    background: #404040;
  }
  canvas:focus {
    outline: red 1px solid;
  }
</style>
  </head>
  <body>
    <noscript>niivue requires JavaScript.</noscript>
    <header>
      <label for="canvasHeight">Height</label>
      <select id="canvasHeight">
        <option value="256">256</option>
        <option value="640" selected>512</option>
        <option value="768">768</option>
      </select>
    </header>
    <main>
      <div class='page-wrapper'>
        <div class='row'>
          <div class='column'>
            <div>
              <canvas id="gl1" height="512">
            </div>
          </div>
          <div class='column'>
            <div>
              <canvas id="gl2" height="512">
            </div>
          </div>
        </div>
        <div class='row'>
          <div class='column'>
            <div>
              <canvas id="gl3" height="512">
            </div>
          </div>
          <div class='column'>
            <div>
              <canvas id="gl4" height="512">
            </div>
          </div>
          
          
        </div>
      </div>
    </main>
    <footer>
      <x id="intensity"> &nbsp;</x>
      <x id="intensity2"> &nbsp;</x>
      <x id="intensity3"> &nbsp;</x>
    </footer>
    <script type="module" async>
      import { Niivue, NVImage, NVMesh } from "./niivue/index.ts";
      canvasHeight.onchange = function () {
        gl1.height = this.value;
        gl2.height = this.value;
        gl3.height = this.value;
        gl4.height = this.value;
        nv1.resizeListener();
        nv2.resizeListener();
        nv3.resizeListener();
        nv4.resizeListener();
      }
      function handleIntensityChange(data) {
        document.getElementById("intensity").innerHTML =
          "&nbsp;&nbsp;" + data.string;
      }
      function handleIntensityChange2(data) {
        document.getElementById("intensity2").innerHTML =
          "&nbsp;&nbsp;" + data.string;
      }
      function handleIntensityChange3(data) {
        document.getElementById("intensity3").innerHTML =
          "&nbsp;&nbsp;" + data.string;
      }
      var nv1 = new Niivue({
        onLocationChange: handleIntensityChange,
        backColor: [1, 1, 1, 1],
      });
      nv1.attachToCanvas(gl1);
      var nv2 = new Niivue({
        onLocationChange: handleIntensityChange2,
        backColor: [1, 1, 1, 1],
      });
      nv2.attachToCanvas(gl2);
      var nv3 = new Niivue({
        onLocationChange: handleIntensityChange3,
        backColor: [1, 1, 1, 1],
      });
      nv3.attachToCanvas(gl3);
      var nv4 = new Niivue({
        show3Dcrosshair: true,
        backColor: [1, 1, 1, 1],
      });
      nv4.attachToCanvas(gl4);
      var volumeList = [{ url: "../demos/images/mni152.nii.gz" }];
      await nv1.loadVolumes(volumeList);
      await nv2.loadVolumes(volumeList);
      await nv3.loadVolumes(volumeList);
      await nv4.loadVolumes(volumeList);
      nv1.setSliceType(nv1.sliceTypeAxial);
      nv2.setSliceType(nv1.sliceTypeCoronal);
      nv3.setSliceType(nv1.sliceTypeSagittal);
      nv4.setSliceType(nv1.sliceTypeRender);
      // make sure all views can control each other
      nv1.broadcastTo([nv2, nv3, nv4], { "3d": true, "2d": true });
      nv2.broadcastTo([nv1, nv3, nv4], { "3d": true, "2d": true });
      nv3.broadcastTo([nv1, nv2, nv4], { "3d": true, "2d": true });
      nv4.broadcastTo([nv1, nv2, nv3], { "3d": true, "2d": true });
    </script>
  </body>
</html>
```

**Closed by neurolabusc** 2024-01-17 13:51 UTC
